# Generated by Django 6.0 on 2025-12-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcoCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('customer_msisdn', models.CharField(max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package', models.CharField(max_length=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('source_reference', models.CharField(max_length=64, unique=True)),
                ('response', models.TextField()),
                ('status_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_reference', models.CharField(max_length=64, unique=True)),
                ('voucher_code', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
