# Generated by Django 6.0 on 2025-12-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('customer_msisdn', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package', models.CharField(max_length=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('source_reference', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
