# Generated by Django 6.0 on 2025-12-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_voucher_transaction_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoucherTransaction',
        ),
    ]
