# Generated by Django 6.0 on 2025-12-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='name',
            new_name='package',
        ),
    ]
